---
title: "Unnamed Twitter Project"
author: "James Hare"
date: "7/11/2020"
output:
  github_document: default
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rtweet)
library(tidytext)
library(lubridate)
```

I wonder who my favorite tweeters are.

```{r favorites}
#This is the code to get favorites, but it shouldn't run automatically due to
#rate limits
#
#james <- get_favorites("ProsccoSocialst", n = 3000)
#write_as_csv(james, "data/james.csv")

james <- read_csv("data/james.csv")

my_fav_tweeters <- james %>%
        group_by(screen_name) %>%
        tally() %>%
        arrange(desc(n)) %>%
        slice(1:10)

ggplot(my_fav_tweeters) +
        geom_col(mapping = aes(reorder(screen_name, n), n)) +
        coord_flip() +
        labs(title = "My Favorite Tweeters",
             x = "Screen Name",
             y = "Number of Favorites")
```

I wonder who their favorites are.

```{r favs_favorites}

#Code that shouldn't run automatically due to rate limits
#
#my_favs_favs <- get_favorites(my_fav_tweeters$screen_name, n = 300)
#write_as_csv(my_favs_favs, "data/my_favs_favs.csv")

my_favs_favs <- read_csv("data/my_favs_favs.csv")

my_favs_fav_tweeters <- my_favs_favs %>%
        group_by(screen_name) %>%
        tally() %>%
        arrange(desc(n)) %>%
        slice(1:10)

ggplot(my_favs_fav_tweeters) +
        geom_col(mapping = aes(reorder(screen_name, n), n)) +
        coord_flip() +
        labs(title = "My Favorite Tweeters' Favorite Tweeters",
             x = "Screen Name",
             y = "Number of Favorites")
```

I'm going to go ahead and follow anyone on this list who I'm not already following.

Let's see which words show up most often in tweets that I have favorited.

```{r}

remove_reg <- "&amp;|&lt;|&gt;"
tidy_james_favs <- james %>%
        filter(!str_detect(text, "^RT")) %>%
        mutate(text = str_remove_all(text, remove_reg)) %>%
        unnest_tokens(word, text, token = "tweets") %>%
        filter(
                !word %in% stop_words$word,!word %in% str_remove_all(stop_words$word, "'"),
                str_detect(word, "[a-z]")
        )

word_count <- tidy_james_favs %>%
        filter(!str_detect(word, "^@")) %>%
        count(word) %>%
        arrange(desc(n)) %>%
        slice(1:20)

ggplot(word_count) +
        geom_col(mapping = aes(reorder(word, n), n)) +
        coord_flip() +
        labs(title = "My Favorite Words",
             x = "Word",
             y = "Number of Occurences")
```

